### ISSUE TITLE
If no filters are applied map is covered in lines

### ISSUE THREAD

**Issue by flinder** [flinder/twitter_flow#5]
It seems like only after one filter is applied (arbitrary) the map is not covered anymore

**Comment by flinder** [comment]
An only when you zoom in or out is the data on the map updated

**Comment by flinder** [comment]
@zero31415  figured out it's just one crazy user. Closing

**Comment by zero31415** [comment]
Sorry just found out all these messages on my forum group of gmail.

**Comment by flinder** [comment]
No problem you solved it anyways :)
